### ISSUE TITLE
 regeneratorRuntime is not defined

### ISSUE THREAD

**Issue by 841660202** [NervJS/awesome-taro#1]
当我使用 withShare.js   https://juejin.im/post/5b99da5d5188255c6f1e084e 装饰器的时候

![image](https://user-images.githubusercontent.com/18305361/48418303-ed289700-e78f-11e8-869a-f5b38647f182.png)

是不是需要安装babel-polyfill

请问该怎么解决呢

**Comment by luckyadam** [comment]
https://nervjs.github.io/taro/docs/before-dev-remind.html#%E5%B0%8F%E7%A8%8B%E5%BA%8F
