### ISSUE TITLE
在使用decorator时报错

### ISSUE THREAD

**Issue by TiamoJrZhang** [NervJS/awesome-taro#17]
![qq 20190219165842](https://user-images.githubusercontent.com/28380327/53002428-a241ae00-3467-11e9-91ab-d1de8f045109.png)
具体试验代码如下：
![qq 20190219170041](https://user-images.githubusercontent.com/28380327/53002568-e92fa380-3467-11e9-8705-e6ddc7791418.png)
![qq 20190219170139](https://user-images.githubusercontent.com/28380327/53002624-0a908f80-3468-11e9-88b3-0411a0a0b649.png)
代码放到react环境下正常运行，这是什么原因，麻烦大佬看下

**Comment by TiamoJrZhang** [comment]
@luckyadam

**Comment by luckyadam** [comment]
@TiamoJrZhang 建议看下 taro 文档吧，taro 和 react 写法还是有一些差异的~

**Comment by chuyun** [comment]
```
export default function MaskHoc(opts = {}) {
  return function maskComponent(Component) {
    class Mask extends Component {
     }


```

**Comment by chuyun** [comment]
```javascript
export default function MaskHoc(opts = {}) {
  return function maskComponent(Component) {
    class Mask extends Component {
       // Do what you want....
     }
  }
}

```
