### ISSUE TITLE
TodoMVC Vue 版 (小程序 / H5)指向的链接不对？

### ISSUE THREAD

**Issue by xixigiggling** [NervJS/awesome-taro#39]
readme中：

+ TodoMVC React 版 (小程序 / H5)
+ TodoMVC Vue 版 (小程序 / H5)

以上两者的链接都指向了react的分支，第二个应该为`https://github.com/NervJS/TodoMVC/tree/vue`？

**Comment by honlyHuang** [comment]
谢谢你咯，已经修正
